# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 17:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'250 Characters Max', max_length=250)),
                ('slug', models.SlugField(help_text=b'Suggested value generated from title. Must be unique.', unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(help_text=b'Suggested value generated from title. Must be unique.', unique_for_date=b'pub_date')),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_html', models.TextField(blank=True, editable=False)),
                ('body', models.TextField()),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, b'Live'), (2, b'Draft'), (3, b'Hidden')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='my_blog.Category')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(unique_for_date=b'pub_date')),
                ('enable_comments', models.BooleanField(default=False)),
                ('post_elsewhere', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
