# Generated by Django 3.1.2 on 2020-10-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20201019_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
