# Generated by Django 3.1.2 on 2020-10-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='link',
            name='enable_comments',
        ),
        migrations.AlterField(
            model_name='entry',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
